{
 "title": "Folder Dashboard Panel performance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": {
     "query": "label_values(grafana_prometheus_request_duration_seconds_count,source)"
    }
   },
   {
    "name": "folder",
    "query": {
     "query": "label_values(grafana_prometheus_request_duration_seconds_count,folder)"
    }
   },
   {
    "name": "dashboard",
    "query": {
     "query": "label_values(grafana_prometheus_request_duration_seconds_count,dashboard)"
    }
   },
   {
    "name": "panel",
    "query": {
     "query": "label_values(grafana_prometheus_request_duration_seconds_count,panel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Folder '$folder'",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "repeat": "folder",
   "targets": [
    {
     "expr": "sum(increase(grafana_prometheus_request_duration_seconds_bucket{folder=\"$folder\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Folder '$folder'",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(grafana_prometheus_request_duration_seconds_bucket{folder=\"$folder\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Folder '$folder'",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(grafana_prometheus_request_duration_seconds_bucket{folder=\"$folder\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Folder '$folder'",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(grafana_prometheus_request_duration_seconds_bucket{folder=\"$folder\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap by Filters",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(grafana_prometheus_request_duration_seconds_bucket{source=~\"$source\",folder=~\"$folder\",dashboard=~\"$dashboard\",panel=~\"$panel\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Panels taking the largest processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(3,sum by (source,folder,dashboard,panel) (increase(grafana_prometheus_request_duration_seconds_sum{folder=~\".+\",dashboard=~\".+\"}[$__interval])))",
     "legendFormat": "{{source}} : {{folder}} / {{dashboard}} / {{panel}}"
    }
   ]
  },
  {
   "title": "Top 100 in the last 24h",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(100, sum by (source,folder,dashboard,panel) (increase(grafana_prometheus_request_duration_seconds_sum[24h])))"
    }
   ]
  }
 ]
}