global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "grafana"
    static_configs:
      - targets:
        # The default Grafana dashboard (at least in Grafana 7) only expects a single
        # grafana instance, which is why I haven't added the other Grafana instances.
        - "grafana_7:3000"
  - job_name: "grafana-proxy"
    static_configs:
      - targets:
        - "rev_proxy:8080"
    metrics_path: "/grafana-proxy/metrics"
